/* eslint-disable no-dupe-keys */
/* eslint-disable react/static-property-placement */
const Languages = {
  ru: {
    Main: 'Главная',
    TasksAndTemplates: 'Задачи и шаблоны',
    Language: 'Язык приложения',
    SystemLog: 'Системные сообщения',
    Phone: 'Телефон',
    TypeMessage: 'Введите сообщение',
    AddTask: 'Добавить задачу',
    Address: 'Адрес',
    Description: 'Описание',
    LastSeenLoggedIn: 'Был активен',
    TreatmentPlan: 'План лечения',
    Treatment: 'Лечение',
    AddPatient: 'Добавить пациента',
    EditPatient: 'Редактировать пациента',
    SelectPhoto: 'Выберите фото',
    Name: 'Имя',
    Surname: 'Фамилия',
    Address: 'Адрес',
    ContactPhone: 'Номер телефона',
    Gender: 'Пол',
    SelectDate: 'Дата рождения',
    Login: 'Логин',
    Password: 'Пароль',
    LogIn: 'Войти',
    Tasks: 'Задачи',
    Templates: 'Шаблоны',
    GenerateSchedule: 'Применить шаблон',
    From: 'С даты',
    To: 'По дату',
    Period: 'Период',
    CheckPatients: 'Выберите пациентов',
    Generate: 'Применить',
    HoursMinutes: 'Часы/Минуты',
    AreYouSureToDelete: 'Действительно хотите удалить?',
    Delete: 'Удалить?',
    Cancel: 'Отмена',
    Yes: 'Да',
    Male: 'Женский',
    Female: 'Мужской',
    EditTask: 'Редактировать задачу',
    CheckType: 'Тип задачи',
    AllowPatientToSetDone: 'Разрешить пациенту выполнять задачу',
    Title: 'Заголовок',
    Task: 'Задача',
    Interval: 'Повторять каждые',
    Time: 'Время',
    AddTemplate: 'Создать шаблон',
    EditTemplate: 'Редактировать шаблон',
    ChooseTime: 'Выберите время',
    ChooseTask: 'Выберите задачу',
    SetAsDone: 'Отметить как сделанное',
    DidntLoggedin: 'Не заходил в приложение',
    WasActive: 'Был активен',
    NoTreatmentPalns: 'Нет плана лечения',
    HowGenerate: 'Как применить?',
    SelectHowToApply: 'Выберите как применить шаблон',
    AddToPrev: 'Добавить к предыдущему',
    SwapWithPrev: 'Заменить по этому шаблону',
    DeletePrev: 'Удалить все предыдущие',
    NoInfo: 'Нет информации',
    Create: 'Создать',
    TemplateDeleted: 'Шаблон успешно удален у пациента',
    ActionWithTask: 'Действие с задачей',
    DeleteOnlyApp: 'Удалить одну задачу',
    DeleteAllThisTasksForUser: 'Удалить все такие задачи для пациента',
    Minute: 'Минута',
    Hour: 'Часов',
    SubmitEdit: 'Подтвердить изменения',
    Observation: 'Обследование',
    PermissionToEdit: 'Разрешение пациенту выполнять задачу',
    Plan: 'План',
    Schedule: 'Расписание пациента',
    TypeMessage: 'Введите сообщение...',
    ErrorOrInternet:
      'Произошла ошибка видимо вы не заполнили обязательные поля или нет подключения к интернету',
    FileNotSent: 'Файл не отправлен. Проверьте ваше соединение',
    Sending: 'Идет отправка',
    FileSent: 'Файл успешно отправлен',
    TreatmentPlan: 'План лечения',
    NeedFeedback: 'Нужен отзыв',
    NotNeedFeedback: 'Не нужен отзыв',
    NeedFeedbackText: 'Нужен текст отзыва',
    ApproveSetDone: 'Подтвердить выполнение?',
    Weight: 'Вес',
    CreateByDrug: 'Создать по лекарству',
    Clear: 'Очистить',
  },
  tm: {
    Main: 'Esasy',
    TasksAndTemplates: 'Ýumuşlar we grafikler',
    Language: 'Programmanyň dili',
    SystemLog: 'Ulgamyň habarlary',
    Phone: 'Telefon',
    TypeMessage: 'Hat ýazyň',
    Address: 'Salgy',
    Description: 'Giňişleýin',
    LastSeenLoggedIn: 'Soňky görünen wagty',
    TreatmentPlan: 'Bejergi grafigi',
    Treatment: 'Bejergi',
    AddPatient: 'Hassa goşmak',
    EditPatient: 'Hassanyň maglumatlaryny üýtgetmek',
    SelectPhoto: 'Suraty saýlaň',
    Name: 'Ady',
    Surname: 'Familiýasy',
    Address: 'Salgy',
    ContactPhone: 'Habarlaşmak üçin telefony',
    Gender: 'Jynsy',
    SelectDate: 'Doglan wagtyny saýlaň',
    Login: 'Login',
    SetAsDone: 'Ýerine ýetirildimi',
    Password: 'Paroly',
    LogIn: 'Içeri gir',
    Tasks: 'Ýumuşlar',
    Templates: 'Grafikler',
    GenerateSchedule: 'Grafikleri ulanyjylara berkitmek',
    From: 'Başlangyjy',
    To: 'Soňy',
    Period: 'Periody',
    CheckPatients: 'Hassalary saýlaň',
    Generate: 'Döret',
    HoursMinutes: 'Sagat/Minut',
    TreatmentPlan: 'Bejergi meýilnamasy',
    AreYouSureToDelete: 'Çyndanam pozmakçymy',
    Delete: 'Pozmak',
    Cancel: 'Ýok',
    Yes: 'Hawa',
    Male: 'Erkek',
    Female: 'Zenan',
    EditTask: 'Ýumuşy üýtgetmek',
    CheckType: 'Görnüşini saýlaň',
    AllowPatientToSetDone: 'Hassa ýerine ýetirendigini tassyklamaga rugsat ber',
    Title: 'Ady',
    Task: 'Ýumuş',
    Interval: 'Aralygy',
    Time: 'Wagty',
    AddTemplate: 'Gradik goş',
    EditTemplate: 'Grafigi üýtget',
    DidntLoggedin: 'Programma girmedi',
    WasActive: 'Soňky gezek programmada boldy',
    NoTreatmentPalns: 'Bejergi grafigi ýok',
    HowGenerate: 'Haýsy usulda ulanmaly?',
    SelectHowToApply: 'Grafigi haýsy usulda ulanmalydygyny saýlaň',
    AddToPrev: 'Öňkilere goşmaly',
    SwapWithPrev: 'Şu grafik boýunça çalyşmaly',
    DeletePrev: 'Öňkileriň ählisini pozmaly',
    AddTask: 'Добавить задачу',
    NoInfo: 'hiç maglumat',
    TemplateDeleted: 'Nusga öçürdi',
    Create: 'Döret',
    ActionWithTask: 'Bu ýumuş bilen amal',
    DeleteOnlyApp: 'Diňe şu ýerde pozmaly',
    Minute: 'Minut',
    Create: 'Döret',
    Hour: 'Sagat',
    ChooseTime: 'Wagt saýlaň',
    DeleteAllThisTasksForUser: 'Bu ýumuşy ähli ýerde pozmaly',
    SubmitEdit: 'Üýtgeşmeleri ýatda saklaň',
    PermissionToEdit: 'Hassa ýerine ýetirmäne rugsat bermek',
    Observation: 'Gözegçilik',
    Schedule: 'Расписание пациента',
    TypeMessage: 'Введите сообщение...',
    Plan: 'План',
    ErrorOrInternet:
      'Ýalňyşlyk ýüze çykdy. Siz haýsydyr bir maglumaty girizmediňiz ýa-da internede baglanşygyňyz ýok',
    FileNotSent: 'Faýl ugradylmady. Internediňizi barlaň',
    Sending: 'Ugradylýar',
    FileSent: 'Faýl üstünlikli ugradyldy',
    NeedFeedback: 'Bahalandyryň',
    NotNeedFeedback: 'Bahalandyrmak gerek däl',
    NeedFeedbackText: 'Teswir ýazmaly',
    ApproveSetDone: 'Ulanyjyň sazlamalaryny tassyklamalymy?',
    Weight: 'Agramy',
    CreateByDrug: 'Derman bilen gönükme döret',
    Clear: 'Arassala',
  },
}

export default Languages
