/* eslint-disable no-dupe-keys */
/* eslint-disable react/static-property-placement */
/* eslint-disable no-dupe-keys */
/* eslint-disable react/static-property-placement */
const Languages = {
  en: {
    Registration: 'Registration',
    Newaccount: 'Create new account',
    Submit: 'Submit',
    loginhere: 'Or you can loginhere',
    Password: 'Password',
    Code: 'Code',
    Noresult: 'No result',
    Item: '/item',
    Loggedin: 'You are not logged in',
    Addadvertisement: 'Add advertisement',
    Searchcategory: 'Search by category',
    Login: 'Login',
    Welcomeback: 'Welcome back!',
    Registerhere: 'Or you can register here',
    Withoutlogin: 'Proceed without login',
    // Audiopermission: 'Proceed without login',
    Inapp: 'In-app Message',
    Call: 'Call',
    Alladvetisementsofthiscompany: 'All advetisements of this company:',
    Description: 'Description',
    Postedat: 'Posted at',
    RetailPrice: 'Retail Price',
    Name: 'Name',
    Neither: 'You are neither logged in nor verified',
    Service: 'Service',
    Product: 'Product',
    Errorocurred: 'Error ocurred',
    Willbeposted: 'Your ad will be posted after review',
    Pickimage: 'Pick image',
    BusinessDescription: 'Business Description',
    Website: 'Website',
    Employeecount: 'Employee count',
    Foundationyear: 'Foundation year',
    Phone: 'Phone',
    Address: 'Address',
    City: 'City',
    Region: 'Region',
    Country: 'Country',
    CompanyName: 'Company Name',
    Accountinfo: 'Account info',
    Maxwhole: 'Max whole. price',
    Minwhole: 'Min whole.',
    SelectAvatar: 'Select Avatar',
    Email: 'E-mail is too short',
    Youcanlogin: 'Now you can login',
    Searchbycategory: 'Search by category',
    Language: 'Language',
  },
  ru: {
    Registration: 'Регистрация',
    Newaccount: 'Создать новый аккаунт',
    Submit: 'Подтвердить',
    loginhere: 'Или можете войти здесь',
    Password: 'Пароль',
    Code: 'Код',
    Noresult: 'Нет результата',
    Item: '/шт',
    Loggedin: 'Вы не авторизированы',
    Addadvertisement: 'Добавить объявлние',
    Searchcategory: 'Искать по категории',
    Login: 'Логин',
    Welcomeback: 'Добро пожаловать!',
    Registerhere: 'Или можете зарегистрироваться здесь',
    Withoutlogin: 'Продолжить без авторизации',
    // Audiopermission: 'Proceed without login',
    Inapp: 'Сообщение',
    Call: 'Звонок',
    Alladvetisementsofthiscompany: 'Все объявления компании:',
    Description: 'Описание',
    Postedat: 'Опубликовано',
    RetailPrice: 'Розничная цена',
    Name: 'Имя',
    Neither: 'Вы не авторизированы',
    Service: 'Услуга',
    Product: 'Продукт',
    Errorocurred: 'Произошла ошибка',
    Willbeposted: 'Ваше объявление будет опубликовано после модерации',
    Pickimage: 'Выбрать картинку',
    BusinessDescription: 'Описание компании',
    Website: 'Веб-сайт',
    Employeecount: 'Кол-во работников',
    Foundationyear: 'Дата образования',
    Phone: 'Телефон',
    Address: 'Адрес',
    City: 'Город',
    Region: 'Регион',
    Country: 'Страна',
    CompanyName: 'Название компании',
    Accountinfo: 'Информация об аккаунте',
    Maxwhole: 'Макс. опт. цена',
    Minwhole: 'Мин. опт. цена',
    SelectAvatar: 'Выбрать аватар',
    Email: 'Введите почту',
    Youcanlogin: 'Сейчас вы можете войти',
    Searchbycategory: 'Поиск по категории',
    Language: 'Язык',
  },
  tm: {
    Registration: 'Hasap açmak',
    Newaccount: 'Täze hasap açmak',
    Submit: 'Ugratmak',
    loginhere: 'Ýa-da içeri giriň',
    Password: 'Parolyňyz',
    Code: 'Kod',
    Noresult: 'Netije ýok',
    Item: '/sany',
    Loggedin: 'Siz içeri girmedik',
    Addadvertisement: 'Bildiriş goşmak',
    Searchcategory: 'Kategoriýa boýunça gözleg',
    Login: 'Içeri gir',
    Welcomeback: 'Hoş geldiňiz!',
    Registerhere: 'Ýa-da hasap açyň',
    Withoutlogin: 'Içeri girman dowam et',
    // Audiopermission: 'Proceed without login',
    Inapp: 'Hat ýazmak',
    Call: 'Jaň etmek',
    Alladvetisementsofthiscompany: 'Kompaniýanyň ähli bildirişleri:',
    Description: 'Giňişleýin',
    Postedat: 'Bildiriş goýlan',
    RetailPrice: 'Eltip berme bahasy',
    Name: 'Ady',
    Neither: 'Siz içeri girmedik ýa-da tassyklanmadyk',
    Service: 'Hyzmat',
    Product: 'Önüm',
    Errorocurred: 'Ýalňyşlyk ýüze çykdy',
    Willbeposted: 'Siziň bildirişiňiz gözden geçirilenden soň çykarylar',
    Pickimage: 'Surat saýlaň',
    BusinessDescription: 'Biznes barada maglumat',
    Website: 'Websaýty',
    Employeecount: 'Işgär sany',
    Foundationyear: 'Düýbi tutulan ýyly',
    Phone: 'Telefon',
    Address: 'Salgysy',
    City: 'Şäheri',
    Region: 'Etraby',
    Country: 'Ýurdy',
    CompanyName: 'Kompaniýanyň ady',
    Accountinfo: 'Hasap barada maglumat',
    Maxwhole: 'Iň gymmat lomaý baha',
    Minwhole: 'Iň arzan lomaý baha',
    SelectAvatar: 'Suratyňyzy saýlaň',
    Email: 'E-mail dogry giriziň',
    Youcanlogin: 'Içeri girip bilersiňiz',
    Searchbycategory: 'Kategoriýa boýunça gözlemek',
    Language: 'Dil',
  },
}

export default Languages
